# Generated by Django 5.2.8 on 2025-11-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legal_name", models.CharField(max_length=255)),
                ("preferred_name", models.CharField(max_length=255)),
                ("professional_title", models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
