# Generated by Django 5.2.8 on 2026-02-04 02:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="decision",
            field=models.CharField(
                choices=[("ALLOW", "ALLOW"), ("DENY", "DENY")],
                default="ALLOW",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="auditlog",
            name="denied_reason",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="request_id",
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="requester_role",
            field=models.CharField(default="employer", max_length=100),
            preserve_default=False,
        ),
    ]
