# Generated by Django 5.2.8 on 2026-02-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_auditlog_decision_auditlog_denied_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="prev_signature",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="signature",
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
